import Routes from '@constants/routes'
import GuardForm from '@containers/GuardForm'
import Navigation from '@containers/Navigation'
import Themed from '@containers/Themed'
import { checkUserIsAuthorized } from '@helpers/authorization'
import { Box } from '@mui/material'
import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const token = await checkUserIsAuthorized(ctx)
  return {
    props: { token },
  }
}

const ComposeGuard: NextPage = () => {
  return (
    <Themed>
      <Box>
        <Head>
          <title>Gandalf - Compose Guard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation title="New Guard" backPath={Routes.home} />

        <Box component="main">
          <GuardForm />
        </Box>
      </Box>
    </Themed>
  )
}

export default ComposeGuard
