import { Box, Button, Typography } from "@mui/material";
import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { checkUserIsAuthorized } from "../helpers/authorization";
import { useAuth } from "../contexts/AuthContext";
import Themed from "../containers/Themed";

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const token = await checkUserIsAuthorized(ctx);
  return {
    props: { token },
  };
};

const Home: NextPage = () => {
  const { signOut } = useAuth();

  return (
    <Themed>
      <Box>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box component="main">
          <Typography variant="h3">Home</Typography>
          <Button onClick={signOut}>Sign out</Button>
        </Box>
      </Box>
    </Themed>
  );
};

export default Home;
