import Routes from '@constants/routes'
import Navigation from '@containers/Navigation'
import Themed from '@containers/Themed'
import { useAuth } from '@contexts/AuthContext'
import { checkUserIsAuthorized } from '@helpers/authorization'
import { Box, Button, Typography } from '@mui/material'
import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const token = await checkUserIsAuthorized(ctx)
  return {
    props: { token },
  }
}

const Home: NextPage = () => {
  const router = useRouter()
  const { signOut } = useAuth()

  const handleSignOut = async () => {
    await signOut()
    router.push(Routes.signIn)
  }

  return (
    <Themed>
      <Box>
        <Head>
          <title>Gandalf</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation title="Home" />

        <Box component="main">
          <Typography variant="h3">Home</Typography>
          <Button onClick={handleSignOut}>Sign out</Button>
        </Box>
      </Box>
    </Themed>
  )
}

export default Home
