name: Run automated tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  unit-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test
